apiVersion: v1
kind: Secret
metadata:
  name: aicoe-tap-gitops-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Deloitte/aicoe-tap-gitops.git
  password: "{{ git_token }}"
  username: admin