apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

resources:
  - prometheus-server-cm.yaml

configMapGenerator:
- name: prometheus-server
  behavior: merge
  namespace: grafana
  files:
    # configfile is used as key
    - alerting_rules.yml=alert-rules.yaml
