apiVersion: v1
kind: Pod
metadata:
  name: grafana-user-multitenancy
  namespace: grafana
spec:
  containers:
    - name: grafana
      image:  {{ aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/aicoe-platform/grafana:v_grafana_multitenancy_0.0.2
      imagePullPolicy: Always
      command: ["/bin/bash","-c","pip install pandas && sh aws-get-object.sh && ls -ltr && python3 grafana.py && echo Process Done!!"]
      env:
        - name: api_url
          value: "http://grafana.grafana.svc.cluster.local/api"
        - name: s3bucket
          value: "{{ platform_metadata_bucket_name }}"
        - name: grafana_admin_id
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-user
        - name: grafana_admin_password
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-password
      volumeMounts:
        - name: grafana-user-csv-data
          mountPath: /dump/utils/grafanausers.csv
          subPath: grafanausers.csv
  volumes:
    - name: grafana-user-csv-data
      configMap:
        name: grafana-multitenancy-cm
  serviceAccountName: sa-grafana
  restartPolicy: Never
