apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minio-cluster-role
rules:
  - verbs:
      - list
      - get
      - patch
      - create
      - delete
    apiGroups:
      - ''
      - authorization.k8s.io
      - rbac.authorization.k8s.io
      - kubeflow.org
      - apps
    resources:
      - profiles
      - secrets
      - deployments
      - pods

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minio-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: sa-minio
    namespace: cserver-minio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-cluster-role