apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-secret-controller
  namespace: cserver-minio
  labels:
    app: minio-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-controller
  template:
    metadata:
      labels:
        app: minio-controller
    spec:
      containers:
      - name: minio
        image: {{ aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/aicoe-platform/minio:v0.0.1
        imagePullPolicy: Always
        command: ["/bin/bash","-c","cd temp && sh aws-get-object.sh && cd .. && python3 minio-sync-secret-controller.py"]
        env:
          - name: cluster_name             
            valueFrom:
              configMapKeyRef:
                name: minio-params
                key: clustername
          - name: s3bucket
            valueFrom:
              configMapKeyRef:
                name: minio-params
                key: s3bucket
      serviceAccount: sa-minio