apiVersion: v1
kind: Service
metadata:
  name: nbexporter
  namespace: nbculling
spec:
  selector:
    app.managed.by: nbpromexporter
  ports:
    - protocol: TCP
      port: 9878
      targetPort: 9878