apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promcustom-role-nb
rules:
  - verbs:
      - list
      - get
      - patch
      - create
      - update
    apiGroups:
      - ''
      - authorization.k8s.io
      - rbac.authorization.k8s.io
      - kubeflow.org
    resources:
      - nodes
      - profiles
      - rolebindings
      - resourcequotas
      - pods
      - notebooks

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promcustom-rolebinding-nb
subjects:
  - kind: ServiceAccount
    name: sa-prom-custom
    namespace: nbculling
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promcustom-role-nb